### ISSUE TITLE
Command line usage 

### ISSUE THREAD

**Issue by ajkarloss** [CFSAN-Biostatistics/shigatyper#1]
Hi, I want to install this tool in HPC environment to run for 100s of isolates. Is there a possibility to make it possible?

**Comment by florathecat** [comment]
Hi,
I don't have HPC environment experience but it's definitely possible as long as you have all the dependencies in place and have the paths set correctly. You can run jupyter notebook from command line using nbconvert, this is how the batch process is driven from the RunNotebook ipynb file, which can definitely be exported/rewritten into a .py file. Please let me know if you have further question.

**Comment by florathecat** [comment]
Actually, crashfrog had already re-org'ed and uploaded the code into a py file for that purpose. Why don't you take a look?

**Comment by crashfrog** [comment]
Actually no, I haven't yet finished the code reorganization that would enable this to work in an HPC environment, but it should be coming out in the next couple of weeks.

**Comment by ajkarloss** [comment]
Thanks. I want to run like "python Shigatyper.py". I will wait. Very nice tool though.

**Comment by crashfrog** [comment]
Well, it turns out it didn't take weeks! Theoretically this is a rough, but running, version. There's an 'environment.yaml` file to configure the conda environment; if you're not using conda you can see the package dependencies at least.

I'm working on a conda package for the whole thing but theoretically you should be able to clone the repo and run it. It'll emit a TSV table to STDOUT that has the sample name (given at the command line, or inferred from your forward reads file), the determination, and presence/absence (-/+) of the ipaB allele. If you run an array job, you should be able to collate all the results using `join` in bash.

**Comment by ajkarloss** [comment]
Awesome. We use conda heavily here. So, it’s perfect. I will try to install it tomorrow.

**Comment by ajkarloss** [comment]
Installed it. Thanks a lot.

**Comment by crashfrog** [comment]
Oh, if it isn’t clear, you should run shigatyper/shigatyper.py, not any of the other files.

**Comment by florathecat** [comment]
Great! Please let us know if it works or not.
